mod commands_finance;
mod commands_infra;
mod commands_ip;
mod commands_ops;
mod commands_social;
mod commands_spectrum;
mod generation;
mod queries;
mod serialization;
mod utils;

#[cfg(test)]
mod tests;

use indexmap::IndexMap;

use gt_common::commands::Command;
use gt_common::types::*;
use rstar::RTree;
use serde::{Deserialize, Serialize};

use crate::components::*;
use crate::events::EventQueue;
use crate::systems;

#[derive(Copy, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpatialNode {
    pub id: EntityId,
    pub pos: [f64; 2],
}

impl rstar::RTreeObject for SpatialNode {
    type Envelope = rstar::AABB<[f64; 2]>;
    fn envelope(&self) -> Self::Envelope {
        rstar::AABB::from_point(self.pos)
    }
}

impl rstar::PointDistance for SpatialNode {
    fn distance_2(&self, point: &[f64; 2]) -> f64 {
        let dx = self.pos[0] - point[0];
        let dy = self.pos[1] - point[1];
        dx * dx + dy * dy
    }
}

/// A predicted disaster event from the forecast system.
/// Generated by peeking ahead in the deterministic RNG to approximate
/// which regions will be hit by disasters in the next 500 ticks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DisasterForecast {
    /// Region entity ID where the disaster is predicted.
    pub region_id: EntityId,
    /// Human-readable region name.
    pub region_name: String,
    /// Tick at which the disaster is predicted to occur.
    pub predicted_tick: Tick,
    /// Estimated probability (0.0-1.0) based on how decisively the RNG roll
    /// would trigger. Higher values indicate stronger certainty.
    pub probability: f64,
    /// Predicted disaster type name (e.g. "Earthquake", "Hurricane").
    pub disaster_type: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct GameWorld {
    config: WorldConfig,
    tick: Tick,
    #[serde(default)]
    speed: GameSpeed,
    next_entity_id: EntityId,
    player_corp_id: Option<EntityId>,

    // Original component storage
    pub positions: IndexMap<EntityId, Position>,
    pub ownerships: IndexMap<EntityId, Ownership>,
    pub financials: IndexMap<EntityId, Financial>,
    pub capacities: IndexMap<EntityId, Capacity>,
    pub healths: IndexMap<EntityId, Health>,
    pub constructions: IndexMap<EntityId, Construction>,
    pub populations: IndexMap<EntityId, Population>,
    pub demands: IndexMap<EntityId, Demand>,
    pub workforces: IndexMap<EntityId, Workforce>,
    pub ai_states: IndexMap<EntityId, AiState>,
    pub policies: IndexMap<EntityId, Policy>,
    pub corporations: IndexMap<EntityId, Corporation>,

    // World generation component storage
    pub land_parcels: IndexMap<EntityId, LandParcelComponent>,
    pub regions: IndexMap<EntityId, RegionComponent>,
    pub cities: IndexMap<EntityId, CityComponent>,

    // Infrastructure component storage
    pub infra_nodes: IndexMap<EntityId, InfraNode>,
    pub infra_edges: IndexMap<EntityId, InfraEdge>,
    pub contracts: IndexMap<EntityId, Contract>,
    pub debt_instruments: IndexMap<EntityId, DebtInstrument>,
    pub tech_research: IndexMap<EntityId, TechResearch>,

    // Advanced gameplay (Phase 10)
    pub auctions: IndexMap<EntityId, Auction>,
    pub acquisition_proposals: IndexMap<EntityId, AcquisitionProposal>,
    pub covert_ops: IndexMap<EntityId, CovertOps>,
    pub lobbying_campaigns: IndexMap<EntityId, LobbyingCampaign>,
    pub achievements: IndexMap<EntityId, AchievementTracker>,
    pub victory_state: Option<VictoryConditions>,

    // Phase 8: Spectrum & Frequency Management
    #[serde(default)]
    pub spectrum_licenses: IndexMap<EntityId, SpectrumLicense>,
    #[serde(default)]
    pub spectrum_auctions: IndexMap<EntityId, SpectrumAuction>,

    // Road network graph (backend spatial data for fiber routing)
    #[serde(default)]
    pub road_network: RoadNetwork,

    // Cable ships per corporation: corp_id → ship count
    #[serde(default)]
    pub cable_ships: IndexMap<EntityId, u32>,

    // Active submarine cable builds: edge_id → corp_id
    #[serde(default)]
    pub active_submarine_builds: IndexMap<EntityId, EntityId>,

    // Co-ownership proposals: node_id → (proposer_corp, target_corp, share_pct)
    #[serde(default)]
    pub co_ownership_proposals: IndexMap<EntityId, (EntityId, EntityId, f64)>,

    // Pending infrastructure upgrade votes: node_id → (proposer_corp, votes_map, start_tick)
    // votes_map: corp_id → boolean (accept/reject)
    #[serde(default)]
    pub pending_upgrade_votes: IndexMap<EntityId, (EntityId, IndexMap<EntityId, bool>, u64)>,

    // Building footprints: entity_id → BuildingFootprint
    // Per-city buildings that serve as demand points for subscriber revenue.
    // Dynamically spawned/destroyed based on city population changes.
    #[serde(default)]
    pub building_footprints: IndexMap<EntityId, crate::components::BuildingFootprint>,

    // Per-city building census: city_id → CityBuildingCensus
    // Tracks building counts and targets for dynamic spawn/destruction.
    #[serde(default)]
    pub city_building_census: IndexMap<EntityId, crate::components::CityBuildingCensus>,

    // Alliance system (Phase 5.1)
    #[serde(default)]
    pub alliances: IndexMap<EntityId, crate::components::alliance::Alliance>,

    // Legal system (Phase 5.2)
    #[serde(default)]
    pub lawsuits: IndexMap<EntityId, crate::components::lawsuit::Lawsuit>,

    // Patent system (Phase 5.3)
    #[serde(default)]
    pub patents: IndexMap<EntityId, Patent>,
    #[serde(default)]
    pub licenses: IndexMap<EntityId, License>,

    // Government Grants (Phase 5.4)
    #[serde(default)]
    pub grants: IndexMap<EntityId, GovernmentGrant>,

    // Stock Market (Phase 6.1)
    #[serde(default)]
    pub stock_market: IndexMap<EntityId, StockMarket>,

    // Satellite System
    #[serde(default)]
    pub satellites: IndexMap<EntityId, Satellite>,
    #[serde(default)]
    pub constellations: IndexMap<EntityId, Constellation>,
    #[serde(default)]
    pub orbital_shells: Vec<crate::components::satellite::OrbitalShell>,
    /// Dynamic satellite edges (ISL + downlinks) — cleared and rebuilt each tick.
    #[serde(default)]
    pub dynamic_satellite_edges: Vec<EntityId>,
    #[serde(default)]
    pub satellite_factories: IndexMap<EntityId, crate::components::satellite::SatelliteFactoryComponent>,
    #[serde(default)]
    pub terminal_factories: IndexMap<EntityId, crate::components::satellite::TerminalFactoryComponent>,
    #[serde(default)]
    pub warehouses: IndexMap<EntityId, crate::components::satellite::WarehouseComponent>,
    #[serde(default)]
    pub launch_pads: IndexMap<EntityId, crate::components::satellite::LaunchPadComponent>,
    /// (city_id, corp_id) → SatelliteSubscription
    #[serde(default)]
    pub satellite_subscriptions: IndexMap<(EntityId, EntityId), crate::components::satellite::SatelliteSubscription>,
    /// Pending contract launches: (rocket_type_str, satellite_ids)
    #[serde(default)]
    pub pending_contract_launches: Vec<(String, Vec<EntityId>)>,
    /// Active satellite service missions
    #[serde(default)]
    pub service_missions: Vec<crate::components::satellite::ServiceMission>,

    // Regional pricing: (corp_id, region_id) → RegionPricing
    #[serde(default)]
    pub region_pricing: IndexMap<(EntityId, EntityId), crate::components::RegionPricing>,

    // Maintenance priorities: entity_id → MaintenancePriority
    #[serde(default)]
    pub maintenance_priorities: IndexMap<EntityId, crate::components::MaintenancePriority>,

    // Per-system timing from last tick (microseconds). Runtime profiling only.
    #[serde(default)]
    #[serde(skip)]
    pub system_times: IndexMap<String, u64>,

    /// Dirty flags for conditional system skipping.
    /// Each bit corresponds to one system — if clear, the system can be skipped.
    /// Commands and events set the relevant bits. Reset after each tick.
    #[serde(default)]
    #[serde(skip)]
    pub dirty_flags: u64,

    // Intel levels: (spy_corp, target_corp) → intel level (0..3)
    // 0 = infra positions only (default), 1 = basic financials (ranges),
    // 2 = detailed financials (exact), 3 = operational data (utilization, health, throughput)
    #[serde(with = "gt_common::serde_helpers::entity_pair_map")]
    pub intel_levels: IndexMap<(EntityId, EntityId), u8>,

    // Mappings for fast lookup
    pub cell_to_parcel: IndexMap<usize, EntityId>,
    pub cell_to_region: IndexMap<usize, EntityId>,
    pub cell_to_city: IndexMap<usize, EntityId>,
    pub corp_infra_nodes: IndexMap<EntityId, Vec<EntityId>>,

    // World grid reference (used by systems for spatial queries)
    pub grid_cell_count: usize,
    pub grid_cell_positions: Vec<(f64, f64)>, // (lat, lon) for each cell
    pub grid_cell_neighbors: Vec<Vec<usize>>, // adjacency list per cell
    /// Average distance between neighboring grid cells in km.
    /// Used by coverage system to scale coverage radii to the grid resolution.
    pub cell_spacing_km: f64,

    // Per-cell coverage data (recalculated each tick by coverage system)
    #[serde(skip)]
    pub cell_coverage: IndexMap<usize, crate::systems::coverage::CellCoverage>,

    // Traffic flow data (computed by utilization system)
    pub traffic_matrix: gt_common::types::TrafficMatrix,

    /// Per-node utilization history (last 100 ticks). Updated by utilization system.
    /// Key: entity_id (node or edge), Value: ring buffer of utilization values (0.0-1.0).
    #[serde(default)]
    pub utilization_history: IndexMap<EntityId, std::collections::VecDeque<f64>>,

    // Weather system (Phase 7.5): active weather conditions per region
    #[serde(default)]
    pub weather_conditions: Vec<crate::components::weather::WeatherCondition>,

    // Network graph state
    pub network: gt_infrastructure::NetworkGraph,

    // Spatial Index for hot-path queries
    #[serde(skip)]
    pub spatial_index: RTree<SpatialNode>,

    // RNG for deterministic simulation
    rng_seed: u64,
    tick_rng_counter: u64,

    pub event_queue: EventQueue,
}

impl GameWorld {
    pub fn new(config: WorldConfig) -> Self {
        let rng_seed = config.seed;

        let mut world = Self {
            config: config.clone(),
            tick: 0,
            speed: GameSpeed::Normal,
            next_entity_id: 1,
            player_corp_id: None,
            positions: IndexMap::new(),
            ownerships: IndexMap::new(),
            financials: IndexMap::new(),
            capacities: IndexMap::new(),
            healths: IndexMap::new(),
            constructions: IndexMap::new(),
            populations: IndexMap::new(),
            demands: IndexMap::new(),
            workforces: IndexMap::new(),
            ai_states: IndexMap::new(),
            policies: IndexMap::new(),
            corporations: IndexMap::new(),
            land_parcels: IndexMap::new(),
            regions: IndexMap::new(),
            cities: IndexMap::new(),
            infra_nodes: IndexMap::new(),
            infra_edges: IndexMap::new(),
            contracts: IndexMap::new(),
            debt_instruments: IndexMap::new(),
            tech_research: IndexMap::new(),
            auctions: IndexMap::new(),
            acquisition_proposals: IndexMap::new(),
            covert_ops: IndexMap::new(),
            lobbying_campaigns: IndexMap::new(),
            achievements: IndexMap::new(),
            victory_state: None,
            spectrum_licenses: IndexMap::new(),
            spectrum_auctions: IndexMap::new(),
            road_network: RoadNetwork::new(),
            cable_ships: IndexMap::new(),
            active_submarine_builds: IndexMap::new(),
            co_ownership_proposals: IndexMap::new(),
            building_footprints: IndexMap::new(),
            city_building_census: IndexMap::new(),
            alliances: IndexMap::new(),
            lawsuits: IndexMap::new(),
            patents: IndexMap::new(),
            licenses: IndexMap::new(),
            grants: IndexMap::new(),
            stock_market: IndexMap::new(),
            satellites: IndexMap::new(),
            constellations: IndexMap::new(),
            orbital_shells: crate::components::satellite::OrbitalShell::standard_shells(),
            dynamic_satellite_edges: Vec::new(),
            satellite_factories: IndexMap::new(),
            terminal_factories: IndexMap::new(),
            warehouses: IndexMap::new(),
            launch_pads: IndexMap::new(),
            satellite_subscriptions: IndexMap::new(),
            pending_contract_launches: Vec::new(),
            service_missions: Vec::new(),
            region_pricing: IndexMap::new(),
            maintenance_priorities: IndexMap::new(),
            system_times: IndexMap::new(),
            dirty_flags: u64::MAX, // all dirty on first tick
            intel_levels: IndexMap::new(),
            pending_upgrade_votes: IndexMap::new(),
            cell_to_parcel: IndexMap::new(),
            cell_to_region: IndexMap::new(),
            cell_to_city: IndexMap::new(),
            corp_infra_nodes: IndexMap::new(),
            grid_cell_count: 0,
            grid_cell_positions: Vec::new(),
            grid_cell_neighbors: Vec::new(),
            cell_spacing_km: 100.0,
            cell_coverage: IndexMap::new(),
            traffic_matrix: gt_common::types::TrafficMatrix::default(),
            utilization_history: IndexMap::new(),
            weather_conditions: Vec::new(),
            network: gt_infrastructure::NetworkGraph::new(),
            rng_seed,
            tick_rng_counter: 0,
            event_queue: EventQueue::new(),
            spatial_index: RTree::new(),
        };

        world.generate_world();
        world.seed_buildings();
        world.create_corporations();
        world.seed_tech_tree();
        world.rebuild_spatial_index();

        world
    }

    pub fn rebuild_spatial_index(&mut self) {
        let mut nodes = Vec::with_capacity(self.infra_nodes.len());
        for (&id, _) in &self.infra_nodes {
            if let Some(pos) = self.positions.get(&id) {
                nodes.push(SpatialNode {
                    id,
                    pos: [pos.x, pos.y],
                });
            }
        }
        self.spatial_index = RTree::bulk_load(nodes);
    }

    pub fn allocate_entity(&mut self) -> EntityId {
        let id = self.next_entity_id;
        self.next_entity_id += 1;
        id
    }

    pub fn set_player_corp_id(&mut self, id: EntityId) {
        if id == 0 {
            self.player_corp_id = None;
        } else {
            self.player_corp_id = Some(id);
        }
    }

    /// Create a new player corporation with all required components.
    /// Used by the multiplayer server when a new player joins a world.
    /// Returns the new corporation's EntityId.
    pub fn create_player_corporation(&mut self, name: &str) -> EntityId {
        let era_config = gt_common::config::EraConfig::from_era(self.config.starting_era);
        let difficulty = gt_common::config::DifficultyConfig::from_preset(self.config.difficulty);
        let starting_capital =
            (era_config.starting_capital as f64 * difficulty.starting_capital_multiplier) as Money;

        let corp_id = self.allocate_entity();
        self.corporations
            .insert(corp_id, Corporation::new(name, true));
        self.financials.insert(
            corp_id,
            Financial {
                cash: starting_capital,
                revenue_per_tick: 0,
                cost_per_tick: 0,
                debt: 0,
            },
        );
        self.policies.insert(corp_id, Policy::default());
        self.workforces.insert(
            corp_id,
            Workforce {
                employee_count: 10,
                skill_level: 0.5,
                morale: 0.8,
                salary_per_tick: 1000,
                maintenance_crew_count: 1,
            },
        );
        corp_id
    }

    pub fn deterministic_random(&mut self) -> f64 {
        // Simple LCG for deterministic per-tick randomness
        self.tick_rng_counter = self
            .tick_rng_counter
            .wrapping_mul(6364136223846793005)
            .wrapping_add(self.rng_seed);
        (self.tick_rng_counter >> 33) as f64 / (1u64 << 31) as f64
    }

    pub fn tick(&mut self) {
        if self.speed == GameSpeed::Paused {
            return;
        }
        self.tick += 1;
        self.tick_rng_counter = self.tick.wrapping_mul(self.rng_seed.wrapping_add(1));
        systems::run_all_systems_timed(self);
    }

    /// Process a command using the world's current player_corp_id (single-player mode).
    pub fn process_command(&mut self, command: Command) {
        self.process_command_inner(command);
    }

    /// Process a command on behalf of a specific corporation (multiplayer mode).
    /// Temporarily sets player_corp_id so all cmd_* methods use the correct corp.
    /// Returns a CommandResult with entity IDs and delta ops for broadcasting.
    pub fn process_command_for_corp(
        &mut self,
        command: Command,
        corp_id: EntityId,
    ) -> gt_common::protocol::CommandResult {
        let prev_corp = self.player_corp_id;
        self.player_corp_id = Some(corp_id);
        let result = self.process_command_with_result(command);
        self.player_corp_id = prev_corp;
        result
    }

    /// Internal: process command and return a result with delta ops.
    fn process_command_with_result(
        &mut self,
        command: Command,
    ) -> gt_common::protocol::CommandResult {
        use gt_common::protocol::CommandResult;

        // Set dirty flags based on command category so conditional systems run.
        use crate::systems::*;
        match &command {
            Command::BuildNode { .. } | Command::BuildEdge { .. } | Command::UpgradeNode { .. }
            | Command::DecommissionNode { .. } | Command::UpdateEdgeWaypoints { .. } => {
                mark_dirty(self, DIRTY_CONSTRUCTION);
            }
            Command::BidSpectrum { .. } | Command::AssignSpectrum { .. } | Command::UnassignSpectrum { .. } => {
                mark_dirty(self, DIRTY_SPECTRUM);
            }
            Command::PlaceBid { .. } | Command::DeclareBankruptcy { .. }
            | Command::RequestBailout { .. } | Command::AcceptBailout { .. } => {
                mark_dirty(self, DIRTY_AUCTION);
            }
            Command::LaunchEspionage { .. } | Command::LaunchSabotage { .. }
            | Command::UpgradeSecurity { .. } => {
                mark_dirty(self, DIRTY_COVERT_OPS);
            }
            Command::StartLobbying { .. } | Command::CancelLobbying { .. } => {
                mark_dirty(self, DIRTY_LOBBYING);
            }
            Command::ProposeAlliance { .. } | Command::AcceptAlliance { .. }
            | Command::DissolveAlliance { .. } => {
                mark_dirty(self, DIRTY_ALLIANCE);
            }
            Command::FileLawsuit { .. } | Command::SettleLawsuit { .. }
            | Command::DefendLawsuit { .. } => {
                mark_dirty(self, DIRTY_LEGAL);
            }
            Command::FilePatent { .. } | Command::RequestLicense { .. }
            | Command::SetLicensePrice { .. } | Command::RevokeLicense { .. }
            | Command::StartIndependentResearch { .. } => {
                mark_dirty(self, DIRTY_PATENT);
            }
            Command::BidForGrant { .. } | Command::CompleteGrant { .. } => {
                mark_dirty(self, DIRTY_GRANTS);
            }
            Command::BuildConstellation { .. } | Command::OrderSatellites { .. }
            | Command::ScheduleLaunch { .. } | Command::ContractLaunch { .. } => {
                mark_dirty(self, DIRTY_LAUNCH | DIRTY_MANUFACTURING);
            }
            Command::ServiceSatellite { .. } => {
                mark_dirty(self, DIRTY_SERVICING);
            }
            _ => {} // Speed, pause, hire/fire, research, etc. — always-run systems handle these
        }

        match command {
            Command::SetSpeed(speed) => {
                self.speed = speed;
                CommandResult::ok()
            }
            Command::TogglePause => {
                self.speed = if self.speed == GameSpeed::Paused {
                    GameSpeed::Normal
                } else {
                    GameSpeed::Paused
                };
                CommandResult::ok()
            }
            Command::BuildNode {
                node_type,
                lon,
                lat,
            } => self.cmd_build_node(node_type, lon, lat),
            Command::BuildEdge {
                edge_type,
                from,
                to,
                waypoints,
                deployment,
            } => self.cmd_build_edge(edge_type, from, to, waypoints, deployment),
            Command::UpdateEdgeWaypoints {
                edge,
                waypoints,
                deployment,
            } => self.cmd_update_edge_waypoints(edge, waypoints, deployment),
            Command::UpgradeNode { entity } => self.cmd_upgrade_node(entity),
            Command::DecommissionNode { entity } => self.cmd_decommission_node(entity),
            Command::TakeLoan {
                corporation,
                amount,
            } => {
                self.cmd_take_loan(corporation, amount);
                CommandResult::ok()
            }
            Command::RepayLoan { loan, amount } => {
                self.cmd_repay_loan(loan, amount);
                CommandResult::ok()
            }
            Command::SetBudget {
                corporation,
                category,
                amount,
            } => {
                if let Some(policy) = self.policies.get_mut(&corporation) {
                    policy.set(format!("budget_{}", category), amount.to_string());
                }
                CommandResult::ok()
            }
            Command::ProposeContract { from, to, terms } => {
                self.cmd_propose_contract(from, to, &terms);
                CommandResult::ok()
            }
            Command::AcceptContract { contract } => {
                if let Some(c) = self.contracts.get_mut(&contract) {
                    c.activate(self.tick);
                    let event = gt_common::events::GameEvent::ContractAccepted { entity: contract };
                    self.event_queue.push(self.tick, event);
                }
                CommandResult::ok()
            }
            Command::RejectContract { contract } => {
                self.contracts.shift_remove(&contract);
                CommandResult::ok()
            }
            Command::StartResearch { corporation, tech } => {
                self.cmd_start_research(corporation, &tech);
                CommandResult::ok()
            }
            Command::CancelResearch { corporation } => {
                // Find active research for this corp and remove it
                let to_remove: Vec<EntityId> = self
                    .tech_research
                    .iter()
                    .filter(|(_, r)| r.researcher == Some(corporation) && !r.completed)
                    .map(|(&id, _)| id)
                    .collect();
                for id in to_remove {
                    self.tech_research.shift_remove(&id);
                }
                CommandResult::ok()
            }
            Command::HireEmployee { corporation, .. } => {
                if let Some(wf) = self.workforces.get_mut(&corporation) {
                    // Per-employee cost = total salary budget / current headcount
                    let per_employee = if wf.employee_count > 0 {
                        wf.salary_per_tick / wf.employee_count as Money
                    } else {
                        wf.salary_per_tick
                    };
                    wf.employee_count += 1;
                    if let Some(fin) = self.financials.get_mut(&corporation) {
                        fin.cost_per_tick += per_employee;
                    }
                    // Scale total salary budget to match new headcount
                    wf.salary_per_tick += per_employee;
                }
                CommandResult::ok()
            }
            Command::FireEmployee { entity } => {
                // entity here refers to the corporation
                if let Some(wf) = self.workforces.get_mut(&entity) {
                    if wf.employee_count > 1 {
                        let per_employee = wf.salary_per_tick / wf.employee_count as Money;
                        wf.employee_count -= 1;
                        wf.salary_per_tick -= per_employee;
                        if let Some(fin) = self.financials.get_mut(&entity) {
                            fin.cost_per_tick -= per_employee;
                        }
                    }
                }
                CommandResult::ok()
            }
            Command::SetPolicy {
                corporation,
                policy,
                value,
            } => {
                if let Some(p) = self.policies.get_mut(&corporation) {
                    p.set(policy, value);
                }
                CommandResult::ok()
            }
            Command::RepairNode { entity, emergency } => {
                self.cmd_repair_node(entity, emergency);
                CommandResult::ok()
            }
            Command::RepairEdge { edge, emergency } => {
                self.cmd_repair_edge(edge, emergency);
                CommandResult::ok()
            }
            Command::EmergencyRepair { entity } => {
                // Legacy command — treat as emergency node repair
                self.cmd_repair_node(entity, true);
                CommandResult::ok()
            }
            Command::CreateSubsidiary { parent, name } => {
                self.cmd_create_subsidiary(parent, &name);
                CommandResult::ok()
            }
            Command::PurchaseInsurance { node } => {
                self.cmd_purchase_insurance(node);
                CommandResult::ok()
            }
            Command::CancelInsurance { node } => {
                if let Some(n) = self.infra_nodes.get_mut(&node) {
                    n.insured = false;
                }
                CommandResult::ok()
            }
            // Bankruptcy & Auctions
            Command::DeclareBankruptcy { entity } => {
                self.cmd_declare_bankruptcy(entity);
                CommandResult::ok()
            }
            Command::RequestBailout { entity } => {
                self.cmd_request_bailout(entity);
                CommandResult::ok()
            }
            Command::AcceptBailout { entity } => {
                self.cmd_accept_bailout(entity);
                CommandResult::ok()
            }
            Command::PlaceBid { auction, amount } => {
                self.cmd_place_bid(auction, amount);
                CommandResult::ok()
            }

            // Stock Market
            Command::BuyShares { corporation, count } => {
                self.cmd_buy_shares(corporation, count);
                CommandResult::ok()
            }
            Command::SellShares { corporation, count } => {
                self.cmd_sell_shares(corporation, count);
                CommandResult::ok()
            }

            // Mergers & Acquisitions
            Command::ProposeAcquisition { target, offer } => {
                self.cmd_propose_acquisition(target, offer);
                CommandResult::ok()
            }
            Command::RespondToAcquisition { proposal, accept } => {
                self.cmd_respond_to_acquisition(proposal, accept);
                CommandResult::ok()
            }

            // Espionage & Sabotage
            Command::LaunchEspionage { target, region } => {
                self.cmd_launch_espionage(target, region);
                CommandResult::ok()
            }
            Command::LaunchSabotage { target, node } => {
                self.cmd_launch_sabotage(target, node);
                CommandResult::ok()
            }
            Command::UpgradeSecurity { level } => {
                self.cmd_upgrade_security(level);
                CommandResult::ok()
            }

            // Lobbying
            Command::StartLobbying {
                region,
                policy,
                budget,
            } => {
                self.cmd_start_lobbying(region, &policy, budget);
                CommandResult::ok()
            }
            Command::CancelLobbying { lobby_id } => {
                self.lobbying_campaigns.shift_remove(&lobby_id);
                CommandResult::ok()
            }

            // Cooperative Infrastructure
            Command::ProposeCoOwnership {
                node,
                target_corp,
                share_pct,
            } => {
                self.cmd_propose_co_ownership(node, target_corp, share_pct);
                CommandResult::ok()
            }
            Command::RespondCoOwnership { proposal, accept } => {
                self.cmd_respond_co_ownership(proposal, accept);
                CommandResult::ok()
            }
            Command::ProposeBuyout {
                node,
                target_corp,
                price,
            } => {
                self.cmd_propose_buyout(node, target_corp, price);
                CommandResult::ok()
            }
            Command::VoteUpgrade { node, approve } => {
                self.cmd_vote_upgrade(node, approve);
                CommandResult::ok()
            }

            // Spectrum & Frequency Management (Phase 8)
            Command::BidSpectrum { band, region, bid } => {
                self.cmd_bid_spectrum(&band, region, bid);
                CommandResult::ok()
            }

            // Spectrum assignment
            Command::AssignSpectrum { node, band } => {
                self.cmd_assign_spectrum(node, &band);
                CommandResult::ok()
            }

            // Spectrum unassignment (carrier aggregation)
            Command::UnassignSpectrum { node, band } => {
                self.cmd_unassign_spectrum(node, &band);
                CommandResult::ok()
            }

            // Cable ship purchase
            Command::PurchaseCableShip => {
                self.cmd_purchase_cable_ship();
                CommandResult::ok()
            }

            // Regional Pricing
            Command::SetRegionPricing {
                region,
                tier,
                price_per_unit,
            } => {
                if let Some(corp_id) = self.player_corp_id {
                    let price_tier = crate::components::PriceTier::parse_str(&tier);
                    self.region_pricing.insert(
                        (corp_id, region),
                        crate::components::RegionPricing {
                            corp_id,
                            region_id: region,
                            tier: price_tier,
                            price_per_unit,
                        },
                    );
                    self.event_queue.push(
                        self.tick,
                        gt_common::events::GameEvent::PricingChanged {
                            corporation: corp_id,
                            region,
                            tier,
                        },
                    );
                }
                CommandResult::ok()
            }

            // Maintenance Priority
            Command::SetMaintenancePriority {
                entity,
                priority,
                auto_repair,
            } => {
                let tier = crate::components::MaintenanceTier::parse_str(&priority);
                self.maintenance_priorities.insert(
                    entity,
                    crate::components::MaintenancePriority { tier, auto_repair },
                );
                self.event_queue.push(
                    self.tick,
                    gt_common::events::GameEvent::MaintenancePrioritySet { entity, priority },
                );
                CommandResult::ok()
            }

            // Alliance (Phase 5.1)
            Command::ProposeAlliance {
                target_corp,
                name,
                revenue_share,
            } => {
                self.cmd_propose_alliance(target_corp, &name, revenue_share);
                CommandResult::ok()
            }
            Command::AcceptAlliance { alliance_id } => {
                self.cmd_accept_alliance(alliance_id);
                CommandResult::ok()
            }
            Command::DissolveAlliance { alliance_id } => {
                self.cmd_dissolve_alliance(alliance_id);
                CommandResult::ok()
            }

            // Legal (Phase 5.2)
            Command::FileLawsuit {
                defendant,
                lawsuit_type,
                damages,
            } => {
                self.cmd_file_lawsuit(defendant, &lawsuit_type, damages);
                CommandResult::ok()
            }
            Command::SettleLawsuit { lawsuit_id } => {
                self.cmd_settle_lawsuit(lawsuit_id);
                CommandResult::ok()
            }
            Command::DefendLawsuit { lawsuit_id } => {
                // Defend is a no-op acknowledgement — lawsuit proceeds to resolution naturally
                let _ = lawsuit_id;
                CommandResult::ok()
            }

            // Patents & Licensing (Phase 5.3)
            Command::FilePatent { tech_id } => {
                self.cmd_file_patent(tech_id);
                CommandResult::ok()
            }
            Command::RequestLicense { patent_id } => {
                self.cmd_request_license(patent_id);
                CommandResult::ok()
            }
            Command::SetLicensePrice {
                patent_id,
                price,
                license_type,
                per_unit_price,
                lease_duration,
            } => {
                self.cmd_set_license_price(patent_id, price, &license_type, per_unit_price, lease_duration);
                CommandResult::ok()
            }
            Command::RevokeLicense { license_id } => {
                self.cmd_revoke_license(license_id);
                CommandResult::ok()
            }
            Command::StartIndependentResearch { tech_id, premium } => {
                self.cmd_start_independent_research(tech_id, premium);
                CommandResult::ok()
            }

            // Government Grants (Phase 5.4)
            Command::BidForGrant { grant_id } => {
                self.cmd_bid_for_grant(grant_id);
                CommandResult::ok()
            }
            Command::CompleteGrant { grant_id } => {
                self.cmd_complete_grant(grant_id);
                CommandResult::ok()
            }

            // Satellite System
            Command::BuildConstellation {
                name,
                orbit_type,
                num_planes,
                sats_per_plane,
                altitude_km,
                inclination_deg,
            } => self.cmd_build_constellation(name, &orbit_type, num_planes, sats_per_plane, altitude_km, inclination_deg),

            Command::OrderSatellites {
                factory,
                constellation_id,
                count,
            } => {
                if let Some(f) = self.satellite_factories.get_mut(&factory) {
                    f.queue.push((constellation_id, count));
                }
                CommandResult::ok()
            }

            Command::ScheduleLaunch {
                launch_pad,
                rocket_type,
                satellites,
            } => {
                if let Some(pad) = self.launch_pads.get_mut(&launch_pad) {
                    pad.launch_queue.push((rocket_type, satellites));
                }
                CommandResult::ok()
            }

            Command::ContractLaunch {
                rocket_type,
                satellites,
            } => {
                self.pending_contract_launches
                    .push((rocket_type, satellites));
                CommandResult::ok()
            }

            Command::DeorbitSatellite { satellite } => {
                if let Some(sat) = self.satellites.get_mut(&satellite) {
                    sat.status = gt_common::types::SatelliteStatus::Deorbiting;
                    let owner = self.ownerships.get(&satellite).map(|o| o.owner).unwrap_or(0);
                    self.event_queue.push(
                        self.tick,
                        gt_common::events::GameEvent::SatelliteDeorbited {
                            satellite_id: satellite,
                            owner,
                        },
                    );
                }
                CommandResult::ok()
            }

            Command::OrderTerminals { factory, count } => {
                // Terminals are produced continuously; this just sets target
                let _ = (factory, count);
                CommandResult::ok()
            }

            Command::ShipTerminals {
                factory,
                warehouse,
                count,
            } => {
                // Transfer terminals from factory to warehouse
                if let Some(f) = self.terminal_factories.get_mut(&factory) {
                    let actual = count.min(f.produced_stored);
                    f.produced_stored -= actual;
                    if let Some(w) = self.warehouses.get_mut(&warehouse) {
                        w.terminal_inventory += actual;
                    }
                }
                CommandResult::ok()
            }

            Command::SetSatellitePricing {
                region,
                monthly_rate,
            } => {
                if let Some(corp_id) = self.player_corp_id {
                    let sub_key = (region, corp_id);
                    // Update pricing for all subscriptions in this region for this corp
                    // Actually set it on a per-region basis
                    for ((city_id, cid), sub) in &mut self.satellite_subscriptions {
                        if *cid == corp_id {
                            // Check if city is in this region
                            if let Some(city) = self.cities.get(city_id) {
                                if city.region_id == region {
                                    sub.monthly_rate = monthly_rate;
                                }
                            }
                        }
                    }
                    let _ = sub_key;
                }
                CommandResult::ok()
            }

            Command::ServiceSatellite {
                satellite,
                service_type,
            } => {
                let st = match service_type.as_str() {
                    "Refuel" => gt_common::types::ServiceType::Refuel,
                    "Repair" => gt_common::types::ServiceType::Repair,
                    _ => gt_common::types::ServiceType::Refuel,
                };
                let cost = match st {
                    gt_common::types::ServiceType::Refuel => 2_000_000,
                    gt_common::types::ServiceType::Repair => 5_000_000,
                };
                self.service_missions
                    .push(crate::components::satellite::ServiceMission {
                        satellite_id: satellite,
                        service_type: st,
                        ticks_remaining: 50, // ~50 ticks for service
                        cost,
                    });
                CommandResult::ok()
            }

            Command::AssignTeam { .. } | Command::SaveGame { .. } | Command::LoadGame { .. } => {
                // Handled externally
                CommandResult::ok()
            }
        }
    }

    /// Legacy wrapper: process command without returning result (for single-player).
    fn process_command_inner(&mut self, command: Command) {
        let _ = self.process_command_with_result(command);
    }

    pub fn transfer_corporation_assets(&mut self, from: EntityId, to: EntityId) {
        // Transfer infrastructure nodes
        let nodes = self.corp_infra_nodes.shift_remove(&from).unwrap_or_default();
        for &node_id in &nodes {
            if let Some(node) = self.infra_nodes.get_mut(&node_id) {
                node.owner = to;
            }
            if let Some(own) = self.ownerships.get_mut(&node_id) {
                own.owner = to;
            }
        }
        self.corp_infra_nodes.entry(to).or_default().extend(nodes);

        // Transfer edge ownership
        for edge in self.infra_edges.values_mut() {
            if edge.owner == from {
                edge.owner = to;
            }
        }

        // Transfer contracts
        for contract in self.contracts.values_mut() {
            if contract.from == from {
                contract.from = to;
            }
            if contract.to == from {
                contract.to = to;
            }
        }

        // Merge financials
        let from_fin = self.financials.shift_remove(&from).unwrap_or(Financial {
            cash: 0,
            revenue_per_tick: 0,
            cost_per_tick: 0,
            debt: 0,
        });
        if let Some(to_fin) = self.financials.get_mut(&to) {
            to_fin.cash += from_fin.cash;
            to_fin.debt += from_fin.debt;
        }

        // Transfer workforce
        if let Some(from_wf) = self.workforces.shift_remove(&from) {
            if let Some(to_wf) = self.workforces.get_mut(&to) {
                to_wf.employee_count += from_wf.employee_count;
            }
        }

        // Transfer debt instruments
        for debt in self.debt_instruments.values_mut() {
            if debt.holder == from {
                debt.holder = to;
            }
        }

        // Remove the absorbed corporation
        self.corporations.shift_remove(&from);
        self.ai_states.shift_remove(&from);
        self.policies.shift_remove(&from);
        self.covert_ops.shift_remove(&from);
        self.achievements.shift_remove(&from);
    }

    pub(super) fn charge_per_unit_fees(&mut self, corp_id: EntityId) {
        let mut charges: Vec<(EntityId, EntityId, Money)> = Vec::new(); // (license_id, holder_corp, charge)

        for (&license_id, license) in self.licenses.iter() {
            if license.licensee_corp != corp_id {
                continue;
            }
            if !matches!(license.license_type, LicenseType::PerUnit) {
                continue;
            }
            if !license.is_active(self.tick) {
                continue;
            }
            let patent = match self.patents.get(&license.patent_id) {
                Some(p) => p,
                None => continue,
            };
            let charge = patent.per_unit_charge();
            if charge > 0 {
                charges.push((license_id, patent.holder_corp, charge));
            }
        }

        for (license_id, holder_corp, charge) in charges {
            // Deduct from licensee
            if let Some(fin) = self.financials.get_mut(&corp_id) {
                fin.cash -= charge;
            }
            // Pay to patent holder
            if let Some(fin) = self.financials.get_mut(&holder_corp) {
                fin.cash += charge;
            }
            // Record usage on the license
            if let Some(license) = self.licenses.get_mut(&license_id) {
                license.record_use(charge);
            }
        }
    }
}
