#!/usr/bin/env bash
set -euo pipefail

# ── GlobalTelco Oracle Cloud Deploy Script ─────────────────────────────────
#
# Usage:
#   ORACLE_IP=<ip> ./deploy/deploy.sh              # Full deploy (build + upload + install)
#   ORACLE_IP=<ip> ./deploy/deploy.sh --upload-only # Skip build, just upload + restart
#   ORACLE_IP=<ip> ./deploy/deploy.sh --setup-only  # First-time server setup (no binary)
#
# Required env vars:
#   ORACLE_IP    — Public IP of your Oracle Cloud instance
#
# Optional env vars:
#   SSH_KEY      — Path to SSH private key (default: ~/.ssh/id_rsa)
#   SSH_USER     — SSH username (default: ubuntu)
#   DB_URL       — Neon PostgreSQL connection string
#   JWT_SECRET   — JWT secret for auth (auto-generated if not set)
#   ADMIN_KEY    — Admin API key (auto-generated if not set)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BINARY="$PROJECT_DIR/target/x86_64-unknown-linux-musl/release/gt-server"

SSH_KEY="${SSH_KEY:-$HOME/.ssh/oracle_globaltelco}"
SSH_USER="${SSH_USER:-ubuntu}"
REMOTE="${SSH_USER}@${ORACLE_IP:?Set ORACLE_IP to your instance public IP}"
SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=no -o ConnectTimeout=10"

echo "╔══════════════════════════════════════════════════╗"
echo "║  GlobalTelco — Oracle Cloud Deploy               ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "  Target: $REMOTE"
echo "  SSH key: $SSH_KEY"
echo ""

# ── Helper ──────────────────────────────────────────────────────────────────

ssh_run() {
    ssh $SSH_OPTS "$REMOTE" "$@"
}

scp_to() {
    scp $SSH_OPTS "$1" "$REMOTE:$2"
}

generate_secret() {
    openssl rand -base64 32
}

# ── Parse args ──────────────────────────────────────────────────────────────

SKIP_BUILD=false
SETUP_ONLY=false

for arg in "$@"; do
    case $arg in
        --upload-only) SKIP_BUILD=true ;;
        --setup-only) SETUP_ONLY=true ;;
    esac
done

# ── Step 1: First-time server setup ────────────────────────────────────────

setup_server() {
    echo ">>> Setting up server (first-time install)..."

    ssh_run "sudo bash -s" <<'SETUP_SCRIPT'
# Create service user
if ! id globaltelco &>/dev/null; then
    sudo useradd -r -s /usr/sbin/nologin -d /opt/globaltelco globaltelco
fi

# Create directories
mkdir -p /opt/globaltelco
chown globaltelco:globaltelco /opt/globaltelco

# Install nginx
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nginx > /dev/null

# Open firewall ports (Ubuntu iptables)
iptables -I INPUT -p tcp --dport 80 -j ACCEPT
iptables -I INPUT -p tcp --dport 443 -j ACCEPT
iptables -I INPUT -p tcp --dport 3001 -j ACCEPT

# Save iptables rules so they persist across reboots
apt-get install -y -qq iptables-persistent > /dev/null
netfilter-persistent save

echo "Server setup complete."
SETUP_SCRIPT
}

# ── Step 2: Cross-compile ──────────────────────────────────────────────────

build_binary() {
    echo ">>> Cross-compiling gt-server for x86_64 Linux (static musl)..."
    cd "$PROJECT_DIR"
    cargo zigbuild --target x86_64-unknown-linux-musl --release --bin gt-server --features postgres 2>&1 | tail -3
    echo "    Binary: $(ls -lh "$BINARY" | awk '{print $5}') at $BINARY"
}

# ── Step 3: Generate .env ──────────────────────────────────────────────────

generate_env() {
    local env_file="$SCRIPT_DIR/.env.production"

    # Only generate if it doesn't exist
    if [[ -f "$env_file" ]]; then
        echo ">>> Using existing .env.production"
        return
    fi

    echo ">>> Generating .env.production..."

    local jwt_secret="${JWT_SECRET:-$(generate_secret)}"
    local admin_key="${ADMIN_KEY:-$(generate_secret)}"

    cat > "$env_file" <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
GT_HOST=0.0.0.0
GT_PORT=3001
GT_JWT_SECRET=$jwt_secret
GT_ACCESS_TOKEN_EXPIRY=3600
GT_REFRESH_TOKEN_EXPIRY=2592000
GT_DEFAULT_WORLD=Global Telco World
GT_MAX_PLAYERS=8
ADMIN_KEY=$admin_key
RUST_LOG=gt_server=info,tower_http=info

# Neon PostgreSQL — set your connection string below
DATABASE_URL=${DB_URL:-postgresql://neondb_owner:YOUR_PASSWORD@YOUR_HOST/neondb?sslmode=require}
EOF

    echo "    Created $env_file"
    echo "    JWT Secret: ${jwt_secret:0:8}..."
    echo "    Admin Key:  ${admin_key:0:8}..."
    echo ""
    echo "    IMPORTANT: Edit $env_file and set DATABASE_URL to your Neon connection string"
    echo "    if it wasn't provided via DB_URL env var."
}

# ── Step 4: Upload & install ───────────────────────────────────────────────

deploy_binary() {
    echo ">>> Uploading binary..."
    scp_to "$BINARY" "/tmp/gt-server"

    echo ">>> Uploading config files..."
    scp_to "$SCRIPT_DIR/.env.production" "/tmp/gt-server.env"
    scp_to "$SCRIPT_DIR/gt-server.service" "/tmp/gt-server.service"
    scp_to "$SCRIPT_DIR/nginx.conf" "/tmp/globaltelco-nginx.conf"

    echo ">>> Installing on server..."
    ssh_run "sudo bash -s" <<'INSTALL_SCRIPT'
# Stop service if running
systemctl stop globaltelco 2>/dev/null || true

# Install binary
mv /tmp/gt-server /opt/globaltelco/gt-server
chmod +x /opt/globaltelco/gt-server
chown globaltelco:globaltelco /opt/globaltelco/gt-server

# Install env file (only if not already present or if newer)
if [[ ! -f /opt/globaltelco/.env ]]; then
    mv /tmp/gt-server.env /opt/globaltelco/.env
    chown globaltelco:globaltelco /opt/globaltelco/.env
    chmod 600 /opt/globaltelco/.env
else
    echo "Keeping existing .env (use --force-env to overwrite)"
    rm /tmp/gt-server.env
fi

# Install systemd service
mv /tmp/gt-server.service /etc/systemd/system/globaltelco.service
systemctl daemon-reload
systemctl enable globaltelco

# Install nginx config
mv /tmp/globaltelco-nginx.conf /etc/nginx/sites-available/globaltelco
ln -sf /etc/nginx/sites-available/globaltelco /etc/nginx/sites-enabled/globaltelco
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx

# Start the game server
systemctl start globaltelco

echo ""
echo "Service status:"
systemctl status globaltelco --no-pager -l | head -15
INSTALL_SCRIPT
}

# ── Main ───────────────────────────────────────────────────────────────────

if [[ "$SETUP_ONLY" == true ]]; then
    setup_server
    echo ""
    echo "Setup complete! Next: run this script again without --setup-only to deploy."
    exit 0
fi

if [[ "$SKIP_BUILD" != true ]]; then
    build_binary
fi

generate_env
setup_server
deploy_binary

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  Deploy complete!                                ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
DOMAIN="globaltelco.gameservers.kodydennon.com"
echo "  Health check:  curl http://$DOMAIN:3001/health"
echo "  WebSocket:     ws://$DOMAIN:3001/ws"
echo "  REST API:      http://$DOMAIN:3001/api"
echo ""
echo "  Server logs:   ssh $SSH_OPTS $REMOTE 'sudo journalctl -u globaltelco -f'"
echo ""
echo "  Frontend env vars to set:"
echo "    PUBLIC_API_URL=http://$DOMAIN:3001"
echo "    PUBLIC_WS_URL=ws://$DOMAIN:3001/ws"
echo ""
