// ── Procedural building footprint + intra-city street layer ─────────────────
// Generates building footprints (small rectangle polygons) and intra-city
// streets around city centers for both Real Earth and Procgen modes.
// Buildings serve as demand point visualization and urban fabric.
//
// Building generation is deterministic: seeded from city position so the same
// city always produces the same building layout.
//
// Population tiers determine building count, ring radii, and street density:
//   Hamlet (<50k): 20-50 buildings, main road + 2-3 side streets
//   Town (50k-250k): 50-200 buildings, basic grid/radial core
//   City (250k-1M): 200-500 buildings, full street network
//   Metropolis (1M-5M): 500-1000 buildings, dense streets + multiple districts
//   Megalopolis (5M+): 1000-2000 buildings, very dense streets
//
// Street layout styles (based on cityIndex % 4):
//   0 = Grid (American): rectangular grid with main avenues + cross streets
//   1 = Radial (European): ring roads + radial avenues from center
//   2 = Organic (Asian/Old World): irregular winding streets with branching
//   3 = Mixed: grid in outer areas, organic in inner core
//
// Buildings are arranged along generated streets:
//   Downtown: Dense large rectangles along main avenues
//   Commercial: Medium-large rectangles along side streets
//   Residential Inner: Medium rectangles along residential streets
//   Residential Outer: Small rectangles along suburban roads
//   Suburban: Tiny rectangles (sparse, far out)
//
// Dynamic spawn/destruction:
//   updateBuildingsDynamic() compares current population vs. generation tier
//   Population growth: new buildings spawn on suburban fringe (marked "new")
//   Population decline: outer buildings marked "abandoned" (grey, low opacity)
//
// Revenue Model:
// - NAP auto-coverage: serves all buildings within radius. Revenue = base_rate x demand x 0.85 (15% overhead)
// - Manual drop cable: serves specific building. Revenue = base_rate x demand x 1.0 (no overhead)
// - Manual drops are 15-20% more profitable, rewarding micro-management
// - At large scale, policies auto-manage NAP placement (with overhead deduction)

import { PolygonLayer, PathLayer } from '@deck.gl/layers';
import type { Layer } from '@deck.gl/core';
import type { City } from '$lib/wasm/types';
import { getCachedCityStreets } from './roadsLayer';
import type { CityStreet } from './roadsLayer';

// ── Types ──────────────────────────────────────────────────────────────────

export type BuildingZone = 'downtown' | 'commercial' | 'residential_inner' | 'residential_outer' | 'suburban';
export type ConnectionStatus = 'unserved' | 'covered' | 'connected' | 'competitor';
export type CityLayout = 'grid' | 'radial' | 'organic' | 'mixed';
export type PopulationTier = 'hamlet' | 'town' | 'city' | 'metro' | 'megalopolis';

export interface BuildingFootprint {
    polygon: [number, number][];
    color: [number, number, number, number];
    /** Center position for spatial queries */
    cx: number;
    cy: number;
    /** City zone classification */
    zone: BuildingZone;
    /** Demand units generated by this building */
    demandValue: number;
    /** Coverage/connection status relative to the player */
    connectionStatus: ConnectionStatus;
    /** Owner corp ID if served by a competitor (0 = none) */
    providerCorpId: number;
    /** Dynamic status flags */
    isNew?: boolean;
    isAbandoned?: boolean;
    /** City ID this building belongs to */
    cityId?: number;
}

export interface StreetSegment {
    from: [number, number];
    to: [number, number];
    type: 'avenue' | 'street';
}

// ── Constants ──────────────────────────────────────────────────────────────

/** Maximum total buildings rendered at once (performance budget). */
const MAX_VISIBLE_BUILDINGS = 5000;

/** Maximum total street segments across all visible cities (performance budget). */
const MAX_STREET_SEGMENTS = 5000;

/** Demand values by zone type */
const ZONE_DEMAND: Record<BuildingZone, number> = {
    downtown: 100,
    commercial: 60,
    residential_inner: 30,
    residential_outer: 15,
    suburban: 5,
};

/** Default zone colors (Bloomberg terminal aesthetic -- dark navy tones) for procgen */
const ZONE_COLORS_PROCGEN: Record<BuildingZone, [number, number, number, number]> = {
    downtown: [32, 36, 48, 200],
    commercial: [30, 34, 46, 195],
    residential_inner: [28, 32, 44, 190],
    residential_outer: [26, 30, 42, 185],
    suburban: [24, 28, 40, 180],
};

/** Brighter zone colors for Real Earth mode (visible against satellite imagery) */
const ZONE_COLORS_REAL_EARTH: Record<BuildingZone, [number, number, number, number]> = {
    downtown: [140, 145, 165, 210],
    commercial: [120, 125, 145, 200],
    residential_inner: [105, 110, 130, 195],
    residential_outer: [90, 95, 115, 190],
    suburban: [80, 85, 105, 180],
};

/** Active zone color palette — set by setRealEarthMode() */
let ZONE_COLORS: Record<BuildingZone, [number, number, number, number]> = { ...ZONE_COLORS_PROCGEN };

/** Whether real earth rendering is active (brighter buildings with outlines) */
let realEarthMode = false;

/** Set the rendering mode for buildings. Call once during MapRenderer init. */
export function setRealEarthMode(isRealEarth: boolean): void {
    realEarthMode = isRealEarth;
    ZONE_COLORS = isRealEarth ? { ...ZONE_COLORS_REAL_EARTH } : { ...ZONE_COLORS_PROCGEN };
    STATUS_COLORS = isRealEarth ? { ...STATUS_COLORS_REAL_EARTH } : { ...STATUS_COLORS_PROCGEN };
}

/** Connection status override colors */
const STATUS_COLORS_PROCGEN: Record<ConnectionStatus, [number, number, number, number]> = {
    unserved: [60, 60, 70, 150],
    covered: [30, 120, 60, 160],
    connected: [16, 185, 129, 200],
    competitor: [180, 80, 80, 150],
};

/** Brighter status colors for Real Earth mode */
const STATUS_COLORS_REAL_EARTH: Record<ConnectionStatus, [number, number, number, number]> = {
    unserved: [130, 130, 145, 190],
    covered: [40, 180, 80, 210],
    connected: [20, 220, 160, 230],
    competitor: [220, 90, 90, 200],
};

let STATUS_COLORS: Record<ConnectionStatus, [number, number, number, number]> = { ...STATUS_COLORS_PROCGEN };

/** Building zone ring definitions. */
export interface ZoneConfig {
    /** Zone classification */
    zone: BuildingZone;
    /** Fraction of total buildings in this zone. */
    fraction: number;
    /** Building width range in degrees (approximate meters at equator). */
    minSizeDeg: number;
    maxSizeDeg: number;
    /** Building height/width aspect ratio range. */
    minAspect: number;
    maxAspect: number;
}

export const ZONE_CONFIGS: ZoneConfig[] = [
    { zone: 'downtown',           fraction: 0.10, minSizeDeg: 0.00036, maxSizeDeg: 0.00063, minAspect: 0.6, maxAspect: 1.4 },
    { zone: 'commercial',         fraction: 0.15, minSizeDeg: 0.00027, maxSizeDeg: 0.00045, minAspect: 0.6, maxAspect: 1.5 },
    { zone: 'residential_inner',  fraction: 0.25, minSizeDeg: 0.000135,maxSizeDeg: 0.00027, minAspect: 0.5, maxAspect: 1.6 },
    { zone: 'residential_outer',  fraction: 0.30, minSizeDeg: 0.000090,maxSizeDeg: 0.000180,minAspect: 0.7, maxAspect: 1.3 },
    { zone: 'suburban',           fraction: 0.20, minSizeDeg: 0.000072,maxSizeDeg: 0.000135,minAspect: 0.7, maxAspect: 1.2 },
];

// ── Zone radii scaling ──────────────────────────────────────────────────────
// Radii scale linearly with population between these bounds.
// Units: degrees (at equator: 1 deg ~ 111km)
// Small city (50k): use minRadius values
// Megalopolis (10M+): use maxRadius values

interface ZoneRadiiBounds {
    /** Inner radius min/max in degrees */
    innerMin: number;
    innerMax: number;
    /** Outer radius min/max in degrees */
    outerMin: number;
    outerMax: number;
}

/** Radius bounds per zone, keyed by zone name. */
const ZONE_RADII: Record<BuildingZone, ZoneRadiiBounds> = {
    //                              innerMin  innerMax  outerMin  outerMax
    downtown:          { innerMin: 0,       innerMax: 0,       outerMin: 0.009,  outerMax: 0.027  },  // 0-1km -> 0-3km
    commercial:        { innerMin: 0.009,   innerMax: 0.027,   outerMin: 0.027,  outerMax: 0.072  },  // 1-3km -> 3-8km
    residential_inner: { innerMin: 0.027,   innerMax: 0.072,   outerMin: 0.045,  outerMax: 0.135  },  // 3-5km -> 8-15km
    residential_outer: { innerMin: 0.045,   innerMax: 0.135,   outerMin: 0.090,  outerMax: 0.225  },  // 5-10km -> 15-25km
    suburban:          { innerMin: 0.090,   innerMax: 0.225,   outerMin: 0.180,  outerMax: 0.360  },  // 10-20km -> 25-40km
};

// ── Seeded PRNG (deterministic per city) ──────────────────────────────────

/**
 * Simple mulberry32 PRNG seeded from a 32-bit integer.
 * Returns a function that produces the next pseudorandom float in [0, 1).
 */
function mulberry32(seed: number): () => number {
    let state = seed | 0;
    return () => {
        state = (state + 0x6D2B79F5) | 0;
        let t = Math.imul(state ^ (state >>> 15), 1 | state);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

/**
 * Create a deterministic seed from a city's position.
 * Combines lon and lat into a single 32-bit integer.
 */
function citySeed(city: City): number {
    // Mix lat/lon bits for a good spread
    const lonBits = Math.floor((city.x + 180) * 10000);
    const latBits = Math.floor((city.y + 90) * 10000);
    return (lonBits * 2654435761 + latBits * 340573321) | 0;
}

// ── Building count by population tier ─────────────────────────────────────

function buildingCount(population: number): number {
    if (population >= 5000000) return 1000 + Math.min(1000, Math.floor(population / 10000000 * 1000));
    if (population >= 1000000) return 500 + Math.floor((population - 1000000) / 4000000 * 500);
    if (population >= 250000) return 200 + Math.floor((population - 250000) / 750000 * 300);
    if (population >= 50000) return 50 + Math.floor((population - 50000) / 200000 * 150);
    return 20 + Math.floor(population / 50000 * 30);
}

// ── Population tier classification ───────────────────────────────────────

function getPopulationTier(population: number): PopulationTier {
    if (population >= 5000000) return 'megalopolis';
    if (population >= 1000000) return 'metro';
    if (population >= 250000) return 'city';
    if (population >= 50000) return 'town';
    return 'hamlet';
}

function getCityLayout(cityIndex: number): CityLayout {
    const layouts: CityLayout[] = ['grid', 'radial', 'organic', 'mixed'];
    return layouts[cityIndex % 4];
}

// ── Population-scaled zone radii ──────────────────────────────────────────

/**
 * Compute a population interpolation factor [0, 1].
 * 0 at pop <= 50k, 1 at pop >= 10M.
 */
export function popFactor(population: number): number {
    const MIN_POP = 50_000;
    const MAX_POP = 10_000_000;
    if (population <= MIN_POP) return 0;
    if (population >= MAX_POP) return 1;
    return (population - MIN_POP) / (MAX_POP - MIN_POP);
}

function lerp(a: number, b: number, t: number): number {
    return a + (b - a) * t;
}

/**
 * Get inner and outer radii for a zone at a given population.
 */
export function zoneRadii(zone: BuildingZone, population: number): { innerR: number; outerR: number } {
    const t = popFactor(population);
    const bounds = ZONE_RADII[zone];
    return {
        innerR: lerp(bounds.innerMin, bounds.innerMax, t),
        outerR: lerp(bounds.outerMin, bounds.outerMax, t),
    };
}

// ── Intra-city street generation ──────────────────────────────────────────

/** Degrees per meter at equator (approximate). 1 degree ~ 111,320m */
const DEG_PER_METER = 1 / 111_320;

/**
 * Generate intra-city streets based on layout style and population tier.
 * Returns an array of StreetSegment objects.
 *
 * Street generation parameters scale with population:
 *   Hamlet (<50k): main road + 2-3 side streets
 *   Town (50k-250k): basic grid/radial core + some streets
 *   City (250k-1M): full street network
 *   Metro (1M+): dense streets, multiple districts
 */
export function generateCityStreets(
    city: City,
    cityIndex: number,
    populationTier: PopulationTier,
): StreetSegment[] {
    const layout = getCityLayout(cityIndex);
    const rng = mulberry32((citySeed(city) + 7919) | 0); // offset seed so streets differ from buildings
    const latCorr = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));

    // City extent radius in degrees (based on outermost zone)
    const { outerR: cityRadius } = zoneRadii('suburban', city.population);
    if (cityRadius < 0.0001) return [];

    const segments: StreetSegment[] = [];

    switch (layout) {
        case 'grid':
            generateGridStreets(city, rng, latCorr, cityRadius, populationTier, segments);
            break;
        case 'radial':
            generateRadialStreets(city, rng, latCorr, cityRadius, populationTier, segments);
            break;
        case 'organic':
            generateOrganicStreets(city, rng, latCorr, cityRadius, populationTier, segments);
            break;
        case 'mixed':
            // Organic in the inner core (downtown + commercial radius)
            {
                const innerRadius = zoneRadii('commercial', city.population).outerR;
                generateOrganicStreets(city, rng, latCorr, innerRadius, populationTier, segments);
            }
            // Grid in the outer areas
            generateGridStreets(city, rng, latCorr, cityRadius, populationTier, segments, 0.3);
            break;
    }

    return segments;
}

/**
 * Grid (American) layout: rectangular street grid within city radius.
 * Main avenues every ~500m (wide), cross streets every ~200m (narrow).
 * Grid is rotated by a seed-based angle.
 */
function generateGridStreets(
    city: City,
    rng: () => number,
    latCorr: number,
    cityRadius: number,
    tier: PopulationTier,
    out: StreetSegment[],
    startFraction: number = 0,
): void {
    // Rotation angle for the grid (seed-based, slight)
    const gridAngle = (rng() - 0.5) * 0.4; // +/- ~23 degrees
    const cos = Math.cos(gridAngle);
    const sin = Math.sin(gridAngle);

    // Spacing in degrees
    const avenueSpacingDeg = 500 * DEG_PER_METER;  // ~500m between avenues
    const streetSpacingDeg = 200 * DEG_PER_METER;   // ~200m between cross streets

    // Determine grid extent based on tier
    let gridExtent = cityRadius * 0.6; // default: 60% of city radius
    if (tier === 'hamlet') gridExtent = cityRadius * 0.2;
    else if (tier === 'town') gridExtent = cityRadius * 0.35;
    else if (tier === 'metro' || tier === 'megalopolis') gridExtent = cityRadius * 0.75;

    const startExtent = gridExtent * startFraction;

    // Generate E-W avenues
    const numAvenues = Math.floor((gridExtent * 2) / avenueSpacingDeg);
    for (let i = 0; i <= numAvenues; i++) {
        const yOff = -gridExtent + i * avenueSpacingDeg;
        if (Math.abs(yOff) < startExtent) continue;
        // Line from -gridExtent to +gridExtent along rotated axis
        const x1 = -gridExtent;
        const x2 = gridExtent;
        // Rotate and translate
        const from: [number, number] = [
            city.x + (x1 * cos - yOff * sin) * latCorr,
            city.y + (x1 * sin + yOff * cos),
        ];
        const to: [number, number] = [
            city.x + (x2 * cos - yOff * sin) * latCorr,
            city.y + (x2 * sin + yOff * cos),
        ];
        out.push({ from, to, type: 'avenue' });
    }

    // Generate N-S cross streets
    const numStreets = Math.floor((gridExtent * 2) / streetSpacingDeg);
    // For hamlets, limit cross streets
    const maxCrossStreets = tier === 'hamlet' ? 3 : tier === 'town' ? Math.min(numStreets, 15) : numStreets;
    const step = numStreets > maxCrossStreets ? Math.floor(numStreets / maxCrossStreets) : 1;
    for (let i = 0; i <= numStreets; i += step) {
        const xOff = -gridExtent + i * streetSpacingDeg;
        if (Math.abs(xOff) < startExtent) continue;
        const y1 = -gridExtent;
        const y2 = gridExtent;
        const from: [number, number] = [
            city.x + (xOff * cos - y1 * sin) * latCorr,
            city.y + (xOff * sin + y1 * cos),
        ];
        const to: [number, number] = [
            city.x + (xOff * cos - y2 * sin) * latCorr,
            city.y + (xOff * sin + y2 * cos),
        ];
        out.push({ from, to, type: 'street' });
    }
}

/**
 * Radial (European) layout: ring roads at increasing radii + radial avenues.
 * Central plaza at core. Ring roads every ~300m, radial avenues every 30-45 degrees.
 */
function generateRadialStreets(
    city: City,
    rng: () => number,
    latCorr: number,
    cityRadius: number,
    tier: PopulationTier,
    out: StreetSegment[],
): void {
    const ringSpacingDeg = 300 * DEG_PER_METER; // ~300m between ring roads

    // Determine number of rings and radial avenues based on tier
    let maxRadius = cityRadius * 0.6;
    let numRadials = 8;
    if (tier === 'hamlet') { maxRadius = cityRadius * 0.15; numRadials = 4; }
    else if (tier === 'town') { maxRadius = cityRadius * 0.3; numRadials = 6; }
    else if (tier === 'metro' || tier === 'megalopolis') { maxRadius = cityRadius * 0.75; numRadials = 12; }

    const numRings = Math.max(1, Math.floor(maxRadius / ringSpacingDeg));
    const radialAngleStep = (Math.PI * 2) / numRadials;
    const radialBaseAngle = rng() * Math.PI * 2; // random rotation offset

    // Generate ring roads (approximated as N-gon segments)
    const ringSegments = Math.max(16, numRadials * 2); // segments per ring
    for (let ring = 1; ring <= numRings; ring++) {
        const r = ring * ringSpacingDeg;
        const angleStep = (Math.PI * 2) / ringSegments;
        for (let seg = 0; seg < ringSegments; seg++) {
            const a1 = seg * angleStep;
            const a2 = (seg + 1) * angleStep;
            const from: [number, number] = [
                city.x + r * Math.cos(a1) * latCorr,
                city.y + r * Math.sin(a1),
            ];
            const to: [number, number] = [
                city.x + r * Math.cos(a2) * latCorr,
                city.y + r * Math.sin(a2),
            ];
            out.push({ from, to, type: ring <= 2 ? 'avenue' : 'street' });
        }
    }

    // Generate radial avenues from center to edge
    for (let i = 0; i < numRadials; i++) {
        const angle = radialBaseAngle + i * radialAngleStep;
        // Start from first ring (central plaza)
        const startR = ringSpacingDeg * 0.3;
        const from: [number, number] = [
            city.x + startR * Math.cos(angle) * latCorr,
            city.y + startR * Math.sin(angle),
        ];
        const to: [number, number] = [
            city.x + maxRadius * Math.cos(angle) * latCorr,
            city.y + maxRadius * Math.sin(angle),
        ];
        out.push({ from, to, type: 'avenue' });
    }
}

/**
 * Organic (Asian/Old World) layout: irregular winding streets using random walks.
 * Narrow alleys, occasional wider roads. Uses noise-like random direction.
 */
function generateOrganicStreets(
    city: City,
    rng: () => number,
    latCorr: number,
    cityRadius: number,
    tier: PopulationTier,
    out: StreetSegment[],
): void {
    // Number of main organic roads emanating from center
    let numMainRoads = 5;
    let numBranches = 3;
    let stepsPerRoad = 8;

    if (tier === 'hamlet') { numMainRoads = 2; numBranches = 1; stepsPerRoad = 4; }
    else if (tier === 'town') { numMainRoads = 3; numBranches = 2; stepsPerRoad = 6; }
    else if (tier === 'metro' || tier === 'megalopolis') { numMainRoads = 8; numBranches = 4; stepsPerRoad = 12; }

    const stepLength = cityRadius * 0.12;
    const maxRadius = cityRadius * 0.65;

    for (let road = 0; road < numMainRoads; road++) {
        let angle = (road / numMainRoads) * Math.PI * 2 + (rng() - 0.5) * 0.5;
        let cx = city.x;
        let cy = city.y;

        for (let step = 0; step < stepsPerRoad; step++) {
            // Winding: add random deviation to angle
            angle += (rng() - 0.5) * 0.8;
            const dx = stepLength * Math.cos(angle) * latCorr;
            const dy = stepLength * Math.sin(angle);
            const nx = cx + dx;
            const ny = cy + dy;

            // Check if still within city radius
            const distFromCenter = Math.sqrt(
                ((nx - city.x) / latCorr) ** 2 + (ny - city.y) ** 2
            );
            if (distFromCenter > maxRadius) break;

            out.push({
                from: [cx, cy],
                to: [nx, ny],
                type: step < 2 ? 'avenue' : 'street',
            });

            // Branch off at some steps
            if (step > 0 && step % 2 === 0) {
                for (let br = 0; br < numBranches; br++) {
                    const brAngle = angle + (rng() - 0.5) * 2.0 + (br % 2 === 0 ? Math.PI / 3 : -Math.PI / 3);
                    let bx = nx;
                    let by = ny;
                    const branchSteps = 2 + Math.floor(rng() * 3);
                    const branchStep = stepLength * 0.6;
                    let brDir = brAngle;

                    for (let bs = 0; bs < branchSteps; bs++) {
                        brDir += (rng() - 0.5) * 1.0;
                        const nbx = bx + branchStep * Math.cos(brDir) * latCorr;
                        const nby = by + branchStep * Math.sin(brDir);
                        const brDist = Math.sqrt(
                            ((nbx - city.x) / latCorr) ** 2 + (nby - city.y) ** 2
                        );
                        if (brDist > maxRadius) break;
                        out.push({
                            from: [bx, by],
                            to: [nbx, nby],
                            type: 'street',
                        });
                        bx = nbx;
                        by = nby;
                    }
                }
            }

            cx = nx;
            cy = ny;
        }
    }
}

// ── Building generation ─────────────────────────────────────────────────

/**
 * Generate a single rectangular building footprint polygon.
 * The rectangle is positioned at (cx, cy) with given width/height in degrees,
 * rotated by `angle` radians.
 */
function makeRect(
    cx: number,
    cy: number,
    halfW: number,
    halfH: number,
    angle: number,
): [number, number][] {
    const cos = Math.cos(angle);
    const sin = Math.sin(angle);

    // 4 corners of the rectangle, rotated
    const corners: [number, number][] = [
        [cx + (-halfW * cos - -halfH * sin), cy + (-halfW * sin + -halfH * cos)],
        [cx + (halfW * cos - -halfH * sin), cy + (halfW * sin + -halfH * cos)],
        [cx + (halfW * cos - halfH * sin), cy + (halfW * sin + halfH * cos)],
        [cx + (-halfW * cos - halfH * sin), cy + (-halfW * sin + halfH * cos)],
    ];
    // Close the ring
    corners.push(corners[0]);
    return corners;
}

/**
 * Classify which zone a given distance from center belongs to, at a given population.
 */
function classifyZone(distFromCenter: number, population: number): BuildingZone {
    for (const config of ZONE_CONFIGS) {
        const { outerR } = zoneRadii(config.zone, population);
        if (distFromCenter <= outerR) return config.zone;
    }
    return 'suburban';
}

/**
 * Get building spacing along streets based on zone.
 * Returns spacing in degrees.
 */
function buildingSpacingForZone(zone: BuildingZone): number {
    switch (zone) {
        case 'downtown': return 20 * DEG_PER_METER;        // 20m
        case 'commercial': return 35 * DEG_PER_METER;       // 35m
        case 'residential_inner': return 40 * DEG_PER_METER; // 40m
        case 'residential_outer': return 60 * DEG_PER_METER; // 60m
        case 'suburban': return 100 * DEG_PER_METER;         // 100m
    }
}

/**
 * Get building setback from street centerline in degrees.
 */
function buildingSetbackForZone(zone: BuildingZone): number {
    switch (zone) {
        case 'downtown': return 10 * DEG_PER_METER;
        case 'commercial': return 15 * DEG_PER_METER;
        case 'residential_inner': return 20 * DEG_PER_METER;
        case 'residential_outer': return 25 * DEG_PER_METER;
        case 'suburban': return 30 * DEG_PER_METER;
    }
}

/**
 * Generate buildings aligned to CityStreet geometry from roadsLayer.
 * CityStreets have multi-point paths and typed widths (avenue/main/residential/alley).
 * Buildings are placed along each path segment with appropriate zone sizing:
 *   - avenue: downtown/commercial zone buildings (large footprints)
 *   - main: commercial zone buildings
 *   - residential: residential zone buildings (set back from street)
 *   - alley: small residential/suburban buildings
 */
function generateBuildingsAlongCityStreets(
    city: City,
    cityStreets: CityStreet[],
    maxCount: number,
    rng: () => number,
): BuildingFootprint[] {
    const buildings: BuildingFootprint[] = [];
    const latCorr = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));

    // Map CityStreet type to building zone
    const streetTypeToZone: Record<string, BuildingZone> = {
        avenue: 'downtown',
        main: 'commercial',
        residential: 'residential_inner',
        alley: 'residential_outer',
    };

    for (const street of cityStreets) {
        if (buildings.length >= maxCount) break;

        const zone = streetTypeToZone[street.type] ?? 'residential_inner';
        const spacing = buildingSpacingForZone(zone);
        const setback = buildingSetbackForZone(zone);
        const config = ZONE_CONFIGS.find(c => c.zone === zone) ?? ZONE_CONFIGS[0];

        // Walk along each segment of the multi-point path
        for (let si = 0; si < street.path.length - 1 && buildings.length < maxCount; si++) {
            const p0 = street.path[si];
            const p1 = street.path[si + 1];
            const dx = p1[0] - p0[0];
            const dy = p1[1] - p0[1];
            const segLen = Math.sqrt(dx * dx + dy * dy);
            if (segLen < 1e-8) continue;

            const ndx = dx / segLen;
            const ndy = dy / segLen;
            const perpX = -ndy;
            const perpY = ndx;
            const streetAngle = Math.atan2(dy, dx);

            // Determine zone at segment midpoint (override if too far from center)
            const midX = (p0[0] + p1[0]) / 2;
            const midY = (p0[1] + p1[1]) / 2;
            const distFromCenter = Math.sqrt(
                ((midX - city.x) / latCorr) ** 2 + (midY - city.y) ** 2
            );
            const actualZone = classifyZone(distFromCenter, city.population);
            // Use the more appropriate zone (whichever is further from downtown)
            const effectiveZone = ZONE_CONFIGS.findIndex(c => c.zone === actualZone) >
                ZONE_CONFIGS.findIndex(c => c.zone === zone) ? actualZone : zone;
            const effectiveConfig = ZONE_CONFIGS.find(c => c.zone === effectiveZone) ?? config;
            const effectiveSpacing = buildingSpacingForZone(effectiveZone);
            const effectiveSetback = buildingSetbackForZone(effectiveZone);

            const numBuildings = Math.floor(segLen / effectiveSpacing);
            for (let i = 0; i < numBuildings && buildings.length < maxCount; i++) {
                const t = (i + 0.5) / Math.max(1, numBuildings);
                const baseX = p0[0] + dx * t;
                const baseY = p0[1] + dy * t;

                for (const side of [-1, 1]) {
                    if (buildings.length >= maxCount) break;

                    const along = (rng() - 0.5) * effectiveSpacing * 0.3;
                    const setbackVar = effectiveSetback * (0.8 + rng() * 0.4);
                    const bx = baseX + ndx * along + perpX * setbackVar * side;
                    const by = baseY + ndy * along + perpY * setbackVar * side;

                    const sizeW = effectiveConfig.minSizeDeg + rng() * (effectiveConfig.maxSizeDeg - effectiveConfig.minSizeDeg);
                    const aspect = effectiveConfig.minAspect + rng() * (effectiveConfig.maxAspect - effectiveConfig.minAspect);
                    const sizeH = sizeW * aspect;
                    const halfW = (sizeW * latCorr) / 2;
                    const halfH = sizeH / 2;

                    const angleJitter = (rng() - 0.5) * 0.15;
                    const angle = streetAngle + angleJitter;

                    const baseColor = ZONE_COLORS[effectiveZone];
                    const colorVariation = Math.floor((rng() - 0.5) * 12);
                    const color: [number, number, number, number] = [
                        Math.max(0, Math.min(255, baseColor[0] + colorVariation)),
                        Math.max(0, Math.min(255, baseColor[1] + colorVariation)),
                        Math.max(0, Math.min(255, baseColor[2] + colorVariation)),
                        baseColor[3],
                    ];

                    buildings.push({
                        polygon: makeRect(bx, by, halfW, halfH, angle),
                        color,
                        cx: bx,
                        cy: by,
                        zone: effectiveZone,
                        demandValue: ZONE_DEMAND[effectiveZone],
                        connectionStatus: 'unserved',
                        providerCorpId: 0,
                        cityId: city.id,
                    });
                }
            }
        }
    }

    return buildings;
}

/**
 * Filter CityStreets from roadsLayer that belong to (are near) a specific city.
 * Uses distance-from-center check based on city radius.
 */
function filterCityStreetsForCity(city: City, allStreets: CityStreet[]): CityStreet[] {
    const latCorr = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));
    // Use a generous radius based on population
    const maxR = cityRadiusForFilter(city.population);

    return allStreets.filter(street => {
        // Check if the midpoint of the first segment is within the city
        if (street.path.length < 2) return false;
        const mx = (street.path[0][0] + street.path[Math.min(1, street.path.length - 1)][0]) / 2;
        const my = (street.path[0][1] + street.path[Math.min(1, street.path.length - 1)][1]) / 2;
        const dist = Math.sqrt(((mx - city.x) / latCorr) ** 2 + (my - city.y) ** 2);
        return dist <= maxR;
    });
}

/**
 * Estimate city radius in degrees for street filtering.
 */
function cityRadiusForFilter(population: number): number {
    if (population >= 5_000_000) return 0.35;
    if (population >= 1_000_000) return 0.22;
    if (population >= 250_000) return 0.14;
    if (population >= 50_000) return 0.07;
    return 0.04;
}

/**
 * Generate buildings placed along the given street segments.
 * Buildings are placed on both sides of each street, with appropriate
 * setback and spacing based on their zone classification.
 */
function generateBuildingsAlongStreets(
    city: City,
    streets: StreetSegment[],
    maxCount: number,
    rng: () => number,
): BuildingFootprint[] {
    const buildings: BuildingFootprint[] = [];
    const latCorr = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));

    for (const seg of streets) {
        if (buildings.length >= maxCount) break;

        // Compute street direction and length
        const dx = seg.to[0] - seg.from[0];
        const dy = seg.to[1] - seg.from[1];
        const streetLen = Math.sqrt(dx * dx + dy * dy);
        if (streetLen < 1e-8) continue;

        // Normalized direction and perpendicular
        const ndx = dx / streetLen;
        const ndy = dy / streetLen;
        const perpX = -ndy;
        const perpY = ndx;

        // Street angle for aligning buildings
        const streetAngle = Math.atan2(dy, dx);

        // Determine zone at street midpoint
        const midX = (seg.from[0] + seg.to[0]) / 2;
        const midY = (seg.from[1] + seg.to[1]) / 2;
        const distFromCenter = Math.sqrt(
            ((midX - city.x) / latCorr) ** 2 + (midY - city.y) ** 2
        );
        const zone = classifyZone(distFromCenter, city.population);
        const spacing = buildingSpacingForZone(zone);
        const setback = buildingSetbackForZone(zone);

        // Find the matching ZoneConfig for building sizes
        const config = ZONE_CONFIGS.find(c => c.zone === zone) ?? ZONE_CONFIGS[0];

        // Walk along the street and place buildings on both sides
        const numBuildings = Math.floor(streetLen / spacing);
        for (let i = 0; i < numBuildings && buildings.length < maxCount; i++) {
            const t = (i + 0.5) / numBuildings;
            const baseX = seg.from[0] + dx * t;
            const baseY = seg.from[1] + dy * t;

            // Place on both sides of the street (left and right)
            for (const side of [-1, 1]) {
                if (buildings.length >= maxCount) break;

                // Slight random offset along street
                const along = (rng() - 0.5) * spacing * 0.3;
                // Random setback variation
                const setbackVar = setback * (0.8 + rng() * 0.4);

                const bx = baseX + ndx * along + perpX * setbackVar * side;
                const by = baseY + ndy * along + perpY * setbackVar * side;

                // Building size from zone config
                const sizeW = config.minSizeDeg + rng() * (config.maxSizeDeg - config.minSizeDeg);
                const aspect = config.minAspect + rng() * (config.maxAspect - config.minAspect);
                const sizeH = sizeW * aspect;
                const halfW = (sizeW * latCorr) / 2;
                const halfH = sizeH / 2;

                // Align building to street with slight jitter
                const angleJitter = (rng() - 0.5) * 0.15; // +/- ~8 degrees
                const angle = streetAngle + angleJitter;

                // Color
                const baseColor = ZONE_COLORS[zone];
                const colorVariation = Math.floor((rng() - 0.5) * 12);
                const color: [number, number, number, number] = [
                    Math.max(0, Math.min(255, baseColor[0] + colorVariation)),
                    Math.max(0, Math.min(255, baseColor[1] + colorVariation)),
                    Math.max(0, Math.min(255, baseColor[2] + colorVariation)),
                    baseColor[3],
                ];

                buildings.push({
                    polygon: makeRect(bx, by, halfW, halfH, angle),
                    color,
                    cx: bx,
                    cy: by,
                    zone,
                    demandValue: ZONE_DEMAND[zone],
                    connectionStatus: 'unserved',
                    providerCorpId: 0,
                    cityId: city.id,
                });
            }
        }
    }

    return buildings;
}

/**
 * Fallback: Generate buildings in concentric rings (original method).
 * Used for very small cities without streets, or as a filler.
 */
function generateCityBuildingsRadial(city: City, maxCount: number, rng: () => number): BuildingFootprint[] {
    const buildings: BuildingFootprint[] = [];
    const latCorrectionFactor = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));

    for (const config of ZONE_CONFIGS) {
        const zoneCount = Math.floor(maxCount * config.fraction);
        const { innerR, outerR } = zoneRadii(config.zone, city.population);

        // Skip zone if radius is negligible
        if (outerR < 0.0001) continue;

        for (let i = 0; i < zoneCount && buildings.length < maxCount; i++) {
            // Random position within the ring (polar coordinates)
            const r = innerR + rng() * (outerR - innerR);
            const theta = rng() * Math.PI * 2;

            const bx = city.x + r * Math.cos(theta) * latCorrectionFactor;
            const by = city.y + r * Math.sin(theta);

            // Random building size within zone constraints
            const sizeW = config.minSizeDeg + rng() * (config.maxSizeDeg - config.minSizeDeg);
            const aspect = config.minAspect + rng() * (config.maxAspect - config.minAspect);
            const sizeH = sizeW * aspect;

            // Apply lat correction to width
            const halfW = (sizeW * latCorrectionFactor) / 2;
            const halfH = sizeH / 2;

            // Random rotation (slight, mostly grid-aligned with some randomness)
            const baseAngle = Math.floor(rng() * 4) * (Math.PI / 2);
            const angleJitter = (rng() - 0.5) * 0.3; // +/- ~17 degrees
            const angle = baseAngle + angleJitter;

            // Default color from zone palette with slight per-building variation
            const baseColor = ZONE_COLORS[config.zone];
            const colorVariation = Math.floor((rng() - 0.5) * 12);
            const color: [number, number, number, number] = [
                Math.max(0, Math.min(255, baseColor[0] + colorVariation)),
                Math.max(0, Math.min(255, baseColor[1] + colorVariation)),
                Math.max(0, Math.min(255, baseColor[2] + colorVariation)),
                baseColor[3],
            ];

            buildings.push({
                polygon: makeRect(bx, by, halfW, halfH, angle),
                color,
                cx: bx,
                cy: by,
                zone: config.zone,
                demandValue: ZONE_DEMAND[config.zone],
                connectionStatus: 'unserved',
                providerCorpId: 0,
                cityId: city.id,
            });
        }
    }

    return buildings;
}

/**
 * Generate all building footprints for a single city.
 * When roadsLayer city streets are available, buildings align to that geometry
 * (avenue = downtown, main = commercial, residential = inner residential,
 * alley = outer residential). Falls back to internal street generation or
 * radial placement when roadsLayer data is unavailable.
 */
function generateCityBuildings(city: City, cityIndex: number): { buildings: BuildingFootprint[]; streets: StreetSegment[] } {
    const count = buildingCount(city.population);
    const tier = getPopulationTier(city.population);
    const rng = mulberry32(citySeed(city));

    // Try to use roadsLayer city streets for building alignment (Phase 3.2.3)
    const allCityStreets = getCachedCityStreets();
    if (allCityStreets && allCityStreets.length > 0) {
        const cityStreets = filterCityStreetsForCity(city, allCityStreets);
        if (cityStreets.length > 0) {
            // Generate buildings aligned to roadsLayer street geometry
            const streetBuildings = generateBuildingsAlongCityStreets(city, cityStreets, count, rng);

            // Fill remaining with radial placement if streets didn't yield enough
            if (streetBuildings.length < count) {
                const remaining = count - streetBuildings.length;
                const fillRng = mulberry32((citySeed(city) + 31337) | 0);
                const fillBuildings = generateCityBuildingsRadial(city, remaining, fillRng);
                return {
                    buildings: [...streetBuildings, ...fillBuildings],
                    streets: [], // streets rendered by roadsLayer, not here
                };
            }

            return {
                buildings: streetBuildings.slice(0, count),
                streets: [], // streets rendered by roadsLayer, not here
            };
        }
    }

    // Fallback: generate internal streets and align buildings to them
    const streets = generateCityStreets(city, cityIndex, tier);

    if (streets.length === 0) {
        // No streets (very tiny city) -- use pure radial placement
        return {
            buildings: generateCityBuildingsRadial(city, count, rng),
            streets: [],
        };
    }

    // Generate buildings along internal streets
    const streetBuildings = generateBuildingsAlongStreets(city, streets, count, rng);

    // If streets didn't generate enough buildings, fill remaining with radial placement
    if (streetBuildings.length < count) {
        const remaining = count - streetBuildings.length;
        // Use a secondary RNG to avoid disturbing the main sequence
        const fillRng = mulberry32((citySeed(city) + 31337) | 0);
        const fillBuildings = generateCityBuildingsRadial(city, remaining, fillRng);
        return {
            buildings: [...streetBuildings, ...fillBuildings],
            streets,
        };
    }

    return {
        buildings: streetBuildings.slice(0, count),
        streets,
    };
}

// ── Cached data ────────────────────────────────────────────────────────────

let cachedBuildings: BuildingFootprint[] | null = null;
let cachedShadows: { polygon: [number, number][]; color: [number, number, number, number] }[] | null = null;
let cachedStreets: StreetSegment[] | null = null;
let cachedCityCount: number = 0;
/** Monotonic version counter -- incremented on data or coverage changes. */
let coverageVersion: number = 0;
/** Track population tiers at generation time for dynamic updates. */
let cachedCityTiers: Map<number, PopulationTier> = new Map();

/**
 * Build and cache building footprint and street data from city array.
 * Call once after cities are loaded from WASM.
 *
 * Enforces the MAX_VISIBLE_BUILDINGS budget by generating buildings for
 * the largest cities first and stopping when the budget is reached.
 * Enforces the MAX_STREET_SEGMENTS budget similarly.
 */
export function buildBuildingData(cities: City[]): void {
    if (cities.length === 0) {
        cachedBuildings = [];
        cachedShadows = [];
        cachedStreets = [];
        cachedCityCount = 0;
        cachedCityTiers.clear();
        return;
    }

    // Process cities from largest to smallest so we prioritize big cities
    const sorted = [...cities]
        .filter(c => Math.abs(c.y) <= 85)
        .sort((a, b) => b.population - a.population);

    // Build a deterministic city index map (sorted by ID for determinism)
    const cityIndexMap = new Map<number, number>();
    const citiesByIdOrder = [...cities].sort((a, b) => a.id - b.id);
    citiesByIdOrder.forEach((c, i) => cityIndexMap.set(c.id, i));

    const allBuildings: BuildingFootprint[] = [];
    const allShadows: { polygon: [number, number][]; color: [number, number, number, number] }[] = [];
    const allStreets: StreetSegment[] = [];
    const newTiers = new Map<number, PopulationTier>();

    for (const city of sorted) {
        if (allBuildings.length >= MAX_VISIBLE_BUILDINGS && allStreets.length >= MAX_STREET_SEGMENTS) break;

        const cityIdx = cityIndexMap.get(city.id) ?? 0;
        const { buildings: cityBuildings, streets: cityStreets } = generateCityBuildings(city, cityIdx);
        const tier = getPopulationTier(city.population);
        newTiers.set(city.id, tier);

        // Add streets within budget
        if (allStreets.length < MAX_STREET_SEGMENTS) {
            const streetRemaining = MAX_STREET_SEGMENTS - allStreets.length;
            const streetsToAdd = cityStreets.slice(0, streetRemaining);
            for (const s of streetsToAdd) {
                allStreets.push(s);
            }
        }

        // Add buildings within budget
        if (allBuildings.length < MAX_VISIBLE_BUILDINGS) {
            const remaining = MAX_VISIBLE_BUILDINGS - allBuildings.length;
            const toAdd = cityBuildings.slice(0, remaining);

            for (const b of toAdd) {
                allBuildings.push(b);

                // Generate shadow: offset polygon slightly SE and darker
                const shadowOffset = 0.00003; // ~3m offset
                const latCorr = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));
                const shadowPoly = b.polygon.map(([lon, lat]) => [
                    lon + shadowOffset * latCorr,
                    lat - shadowOffset,
                ] as [number, number]);

                allShadows.push({
                    polygon: shadowPoly,
                    color: [8, 10, 16, 120],
                });
            }
        }
    }

    cachedBuildings = allBuildings;
    cachedShadows = allShadows;
    cachedStreets = allStreets;
    cachedCityCount = cities.length;
    cachedCityTiers = newTiers;
    coverageVersion++;
}

/** Dispose cached building data to free memory. */
export function disposeBuildingData(): void {
    cachedBuildings = null;
    cachedShadows = null;
    cachedStreets = null;
    cachedCityCount = 0;
    cachedCityTiers.clear();
}

// ── Dynamic building spawn/destruction (Gap #14) ──────────────────────────

/**
 * Update buildings dynamically based on population changes.
 * Call when city data updates (every ~30 ticks).
 *
 * - If population grew across a tier threshold: add new buildings on suburban fringe
 * - If population declined: mark outer buildings as "abandoned" (grey, low opacity)
 *
 * Returns true if buildings were modified (layer needs update trigger).
 */
export function updateBuildingsDynamic(cities: City[]): boolean {
    if (!cachedBuildings || cachedBuildings.length === 0) return false;

    let modified = false;

    for (const city of cities) {
        const oldTier = cachedCityTiers.get(city.id);
        const newTier = getPopulationTier(city.population);

        if (!oldTier || oldTier === newTier) continue;

        const tierOrder: PopulationTier[] = ['hamlet', 'town', 'city', 'metro', 'megalopolis'];
        const oldIdx = tierOrder.indexOf(oldTier);
        const newIdx = tierOrder.indexOf(newTier);

        if (newIdx > oldIdx) {
            // Population GREW -- add new buildings on the suburban fringe
            const numNew = Math.min(20, MAX_VISIBLE_BUILDINGS - cachedBuildings.length);
            if (numNew <= 0) continue;

            const rng = mulberry32((citySeed(city) + 99991) | 0);
            const latCorr = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));
            const { innerR, outerR } = zoneRadii('suburban', city.population);

            for (let i = 0; i < numNew; i++) {
                const r = innerR + rng() * (outerR - innerR);
                const theta = rng() * Math.PI * 2;
                const bx = city.x + r * Math.cos(theta) * latCorr;
                const by = city.y + r * Math.sin(theta);

                const config = ZONE_CONFIGS[4]; // suburban
                const sizeW = config.minSizeDeg + rng() * (config.maxSizeDeg - config.minSizeDeg);
                const aspect = config.minAspect + rng() * (config.maxAspect - config.minAspect);
                const sizeH = sizeW * aspect;
                const halfW = (sizeW * latCorr) / 2;
                const halfH = sizeH / 2;
                const angle = rng() * Math.PI;

                // Slightly brighter color to indicate "new" construction
                const color: [number, number, number, number] = [38, 42, 56, 210];

                cachedBuildings.push({
                    polygon: makeRect(bx, by, halfW, halfH, angle),
                    color,
                    cx: bx,
                    cy: by,
                    zone: 'suburban',
                    demandValue: ZONE_DEMAND.suburban,
                    connectionStatus: 'unserved',
                    providerCorpId: 0,
                    isNew: true,
                    cityId: city.id,
                });

                // Add shadow
                if (cachedShadows) {
                    const shadowOffset = 0.00003;
                    const shadowPoly = cachedBuildings[cachedBuildings.length - 1].polygon.map(([lon, lat]) => [
                        lon + shadowOffset * latCorr,
                        lat - shadowOffset,
                    ] as [number, number]);
                    cachedShadows.push({
                        polygon: shadowPoly,
                        color: [8, 10, 16, 120],
                    });
                }
            }

            cachedCityTiers.set(city.id, newTier);
            modified = true;
        } else if (newIdx < oldIdx) {
            // Population DECLINED -- mark some outer buildings as abandoned
            const cityBuildings = cachedBuildings.filter(b => b.cityId === city.id);
            // Sort by distance from center (descending) and mark outermost as abandoned
            const latCorr = 1 / Math.max(0.1, Math.cos((city.y * Math.PI) / 180));
            const withDist = cityBuildings.map(b => ({
                b,
                dist: Math.sqrt(((b.cx - city.x) / latCorr) ** 2 + (b.cy - city.y) ** 2),
            }));
            withDist.sort((a, b) => b.dist - a.dist);

            // Mark ~10% of outer buildings as abandoned
            const numAbandon = Math.max(1, Math.floor(cityBuildings.length * 0.1));
            for (let i = 0; i < Math.min(numAbandon, withDist.length); i++) {
                withDist[i].b.isAbandoned = true;
                withDist[i].b.color = [45, 45, 50, 100]; // grey, low opacity
            }

            cachedCityTiers.set(city.id, newTier);
            modified = true;
        }
    }

    if (modified) {
        coverageVersion++;
    }

    return modified;
}

// ── Coverage update ──────────────────────────────────────────────────────

/**
 * Haversine-approximated squared distance in meters between two lon/lat points.
 * Uses flat-earth approximation for speed (accurate enough within ~50km).
 */
function distSqMeters(lon1: number, lat1: number, lon2: number, lat2: number): number {
    const avgLat = ((lat1 + lat2) / 2) * (Math.PI / 180);
    const cosLat = Math.cos(avgLat);
    const dx = (lon2 - lon1) * cosLat * 111_320;
    const dy = (lat2 - lat1) * 111_320;
    return dx * dx + dy * dy;
}

/**
 * Update building coverage status based on infrastructure node positions.
 *
 * Coverage rules:
 *   - NetworkAccessPoint (NAP): 500m radius, marks buildings as 'covered'
 *   - FiberDistributionHub (FDH): 2000m radius, marks buildings as 'covered'
 *   - Other node types with coverage_factor > 0.5: 300m radius (e.g. SmallCell, CellTower)
 *   - Buildings served by non-player corps get 'competitor' status
 *
 * @param playerNodes Array of infrastructure nodes (from bridge.getAllInfrastructure().nodes)
 * @param playerCorpId The player's corporation ID
 */
export function updateBuildingCoverage(
    playerNodes: Array<{ x: number; y: number; node_type: string; owner: number }>,
    playerCorpId: number
): void {
    if (!cachedBuildings || cachedBuildings.length === 0) return;

    // Reset all buildings to unserved
    for (const b of cachedBuildings) {
        b.connectionStatus = 'unserved';
        b.providerCorpId = 0;
    }

    // Coverage radius in meters per node type
    const NODE_COVERAGE: Record<string, number> = {
        'NetworkAccessPoint': 500,
        'SmallCell': 400,
        'CellTower': 800,
        'FiberDistributionHub': 2000,
        'MacroCell': 1200,
        'WirelessRelay': 600,
    };

    // Squared radii for faster comparison
    const coverageNodes = playerNodes
        .filter(n => NODE_COVERAGE[n.node_type] !== undefined)
        .map(n => ({
            x: n.x,
            y: n.y,
            owner: n.owner,
            radiusSqM: (NODE_COVERAGE[n.node_type]!) ** 2,
        }));

    if (coverageNodes.length === 0) return;

    for (const b of cachedBuildings) {
        for (const node of coverageNodes) {
            const dSq = distSqMeters(b.cx, b.cy, node.x, node.y);
            if (dSq <= node.radiusSqM) {
                if (node.owner === playerCorpId) {
                    // Player coverage -- only upgrade, never downgrade
                    if (b.connectionStatus !== 'connected') {
                        b.connectionStatus = 'covered';
                        b.providerCorpId = playerCorpId;
                    }
                } else {
                    // Competitor coverage -- only set if not already covered by player
                    if (b.connectionStatus === 'unserved') {
                        b.connectionStatus = 'competitor';
                        b.providerCorpId = node.owner;
                    }
                }
            }
        }
    }

    coverageVersion++;
}

/**
 * Get the current cached buildings array (read-only).
 * Used by demand overlay and tooltip system.
 */
export function getCachedBuildings(): BuildingFootprint[] | null {
    return cachedBuildings;
}

// ── Color computation ──────────────────────────────────────────────────────

/**
 * Compute the display color for a building based on its connection status.
 * When no coverage data has been applied, falls back to zone-based defaults.
 */
function getBuildingColor(b: BuildingFootprint): [number, number, number, number] {
    // Abandoned buildings always show grey
    if (b.isAbandoned) {
        return [45, 45, 50, 100];
    }

    switch (b.connectionStatus) {
        case 'covered':
            return STATUS_COLORS.covered;
        case 'connected':
            return STATUS_COLORS.connected;
        case 'competitor':
            return STATUS_COLORS.competitor;
        case 'unserved':
            // Only show grey unserved color if coverage data has actually been applied
            // (coverageVersion > 1 means updateBuildingCoverage has run at least once)
            if (coverageVersion > 1) {
                return STATUS_COLORS.unserved;
            }
            // New buildings get a slightly brighter tint
            if (b.isNew) {
                return [38, 42, 56, 210];
            }
            // Fall through to default zone color
            return b.color;
        default:
            return b.color;
    }
}

/**
 * Compute demand overlay color for a building (warm red/orange intensity scale).
 * Connected buildings show their provider color; unserved show demand heat.
 */
function getDemandOverlayColor(b: BuildingFootprint): [number, number, number, number] {
    // Abandoned buildings show very dim
    if (b.isAbandoned) {
        return [40, 40, 45, 60];
    }

    // Connected / covered by player -- show provider green
    if (b.connectionStatus === 'covered' || b.connectionStatus === 'connected') {
        const intensity = Math.min(1.0, b.demandValue / 100);
        return [
            Math.floor(16 + intensity * 14),
            Math.floor(120 + intensity * 65),
            Math.floor(60 + intensity * 69),
            Math.floor(140 + intensity * 60),
        ];
    }

    // Competitor-served -- show competitor red tint
    if (b.connectionStatus === 'competitor') {
        const intensity = Math.min(1.0, b.demandValue / 100);
        return [
            Math.floor(140 + intensity * 60),
            Math.floor(50 + intensity * 30),
            Math.floor(50 + intensity * 20),
            Math.floor(140 + intensity * 60),
        ];
    }

    // Unserved -- warm red/orange based on demand intensity
    const intensity = Math.min(1.0, b.demandValue / 100);
    return [
        Math.floor(200 + intensity * 55),
        Math.floor(80 + intensity * 60),
        Math.floor(20 + intensity * 20),
        Math.floor(120 + intensity * 80),
    ];
}

// ── Layer creation ─────────────────────────────────────────────────────────

/**
 * Create building footprint and street layers.
 * Returns deck.gl PolygonLayers for shadows + building fills, and PathLayers for streets.
 * Visible at zoom 7+.
 */
export function createBuildingsLayers(currentZoom: number, demandOverlayActive: boolean = false): Layer[] {
    if (currentZoom < 7) return [];

    const layers: Layer[] = [];

    // 1. Street layers (underneath buildings)
    if (cachedStreets && cachedStreets.length > 0) {
        const avenues = cachedStreets.filter(s => s.type === 'avenue');
        const sideStreets = cachedStreets.filter(s => s.type === 'street');

        if (avenues.length > 0) {
            layers.push(new PathLayer({
                id: 'streets-avenues',
                data: avenues,
                getPath: (d: StreetSegment) => [d.from, d.to],
                getColor: [80, 80, 90, 160],
                getWidth: 2,
                widthUnits: 'pixels',
                widthMinPixels: 1,
                widthMaxPixels: 3,
                pickable: false,
                parameters: { depthTest: false },
                capRounded: true,
                jointRounded: true,
            }));
        }

        if (sideStreets.length > 0) {
            layers.push(new PathLayer({
                id: 'streets-side',
                data: sideStreets,
                getPath: (d: StreetSegment) => [d.from, d.to],
                getColor: [60, 60, 70, 120],
                getWidth: 1,
                widthUnits: 'pixels',
                widthMinPixels: 1,
                widthMaxPixels: 2,
                pickable: false,
                parameters: { depthTest: false },
                capRounded: true,
                jointRounded: true,
            }));
        }
    }

    if (!cachedBuildings || cachedBuildings.length === 0) return layers;

    // 2. Shadow layer (offset darker polygons underneath buildings)
    if (cachedShadows && cachedShadows.length > 0) {
        layers.push(new PolygonLayer({
            id: 'buildings-shadows',
            data: cachedShadows,
            getPolygon: (d: { polygon: [number, number][] }) => d.polygon,
            getFillColor: (d: { color: [number, number, number, number] }) => d.color,
            stroked: false,
            filled: true,
            pickable: false,
            parameters: { depthTest: false },
            updateTriggers: {
                getFillColor: [cachedCityCount],
            },
        }));
    }

    // 3. Building fill layer -- color depends on coverage status or demand overlay
    const colorFn = demandOverlayActive ? getDemandOverlayColor : getBuildingColor;

    layers.push(new PolygonLayer({
        id: 'buildings-fill',
        data: cachedBuildings,
        getPolygon: (d: BuildingFootprint) => d.polygon,
        getFillColor: (d: BuildingFootprint) => colorFn(d),
        stroked: realEarthMode,
        getLineColor: realEarthMode ? [180, 185, 200, 160] as [number, number, number, number] : [0, 0, 0, 0] as [number, number, number, number],
        getLineWidth: 1,
        lineWidthUnits: 'pixels' as const,
        lineWidthMinPixels: 1,
        filled: true,
        pickable: currentZoom >= 8,
        autoHighlight: currentZoom >= 8,
        highlightColor: [255, 255, 255, 60],
        parameters: { depthTest: false },
        updateTriggers: {
            getFillColor: [cachedCityCount, coverageVersion, demandOverlayActive, realEarthMode],
        },
    }));

    return layers;
}
